drbd: add more sanity checks, add to save event

diff --git a/root/etc/e-smith/events/actions/nethserver-ha-conf-drbd b/root/etc/e-smith/events/actions/nethserver-ha-conf-drbd
--- a/root/etc/e-smith/events/actions/nethserver-ha-conf-drbd
+++ b/root/etc/e-smith/events/actions/nethserver-ha-conf-drbd
@@ -31,10 +31,20 @@ drbdmeta 0 v08 $disk internal wipe-md --force
 drbdmeta 0 v08 $disk internal create-md --force
 drbdadm up $RES
 
-other_node="192.168.144.51"
 system_name=`config get SystemName`
 if [ "$system_name" == 'ns1' ]; then
     other_node="192.168.144.52"
+elif [ "$system_name" == 'ns2' ]; then
+    other_node="192.168.144.51"
+else
+    echo "Invalid SystemName '$system_name'"
+    exit 1
+fi
+
+virtual_ip=`config getprop ha VirtualIP`
+if [ "x$virtual_ip" == "x" ]; then
+    echo "Virtual IP not set"
+    exit 1
 fi
 
 ping -q -W 1 -c 1 $other_node >/dev/null
@@ -43,7 +53,7 @@ if [ $? -eq 0 ]; then
     exit 0
 fi
 
-virtual_ip=`config getprop ha VirtualIP`
+
 ping -q -W 1 -c 1 $virtual_ip >/dev/null
 if [ $? -eq 0 ]; then
     echo "Virtual IP '$virtual_ip' is online: DRBD creation skipped"
